### ISSUE TITLE
Impression

### ISSUE THREAD

**Issue by simon88** [gthom/gapMea#1]
Ce n'est pas un bug que je souhaite signaler mais plutôt une fonctionnalité. Tout d'abord le logiciel est vraiment super et répond à mes attentes à 100%.
Une petite idée d'amélioration serait de pouvoir imprimer un MCD et pourquoi pas aussi par la même occasion, exporter un MCD en fichier image (JPEG ou autre).

Qu'en pensez vous ?

**Comment by gthom** [comment]
Merci pour votre commentaire.
1) En ce qui concerne l'impression elle se fait par sélection de "Imprimer" dans le menu contextuel de la zone de visualisation (click droit souris) Je l'avoue ce n'est pas très conventionnel ;)
2) En ce qui concerne l'export au format png ou jpeg je suis "pour"

**Comment by simon88** [comment]
Merci pour votre réponse. 

Effectivement je n'avais pas vu le clic droit "imprimer" :).
